-- Oracle SQL*Loader Control File
-- Generated on: 2024-01-15 10:30:00
-- Table: EMPLOYEES
-- Demonstrates Global File Encoding and Partition Features

LOAD DATA CHARACTERSET AL32UTF8
INFILE 'employees_data.csv'
BADFILE 'employees.bad'
DISCARDFILE 'employees.dsc'
SKIP 1
ERRORS 50
ROWS 50000
BINDSIZE 1048576
DIRECT=TRUE

INTO TABLE EMPLOYEES
PARTITION (EMPLOYEES_2024)
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LRTRIM
TRAILING NULLCOLS
(
    EMPLOYEE_ID INTEGER EXTERNAL,
    FIRST_NAME CHAR(20),
    LAST_NAME CHAR(25),
    EMAIL CHAR(25),
    PHONE_NUMBER CHAR(20),
    HIRE_DATE DATE "YYYY-MM-DD",
    JOB_ID CHAR(10),
    SALARY DECIMAL EXTERNAL,
    COMMISSION_PCT DECIMAL EXTERNAL,
    MANAGER_ID INTEGER EXTERNAL,
    DEPARTMENT_ID INTEGER EXTERNAL
) 